[general]
number_of_devices = 200
# device_spacing = 0.03
device_trigger_radius = 90
simulation_steps = 100

[map]
wind_speed = 5
wind_direction = 40
fire_speed_multiplier = 1
initial_fire_size = 0.00005
smoke_area_offset = 0.0025
maps_save_path = "saved_maps"
park_dir = 'maps'
park_file = 'aspromonte.kml'

[common-paths]
data_path = "data"
fire_img_filename = 'fire2.png'
wood_img_filename = 'wood2.png'

